# Generated by Django 4.0.4 on 2022-06-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetdreams_app', '0004_profile_car_profile_mods_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pic_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pic_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
